name: Twingate Connector
version: "1.0.0"
slug: "twingate_connector"
description: "Runs the Twingate Connector inside Home Assistant OS"
arch:
  - amd64
  - armv7
  - aarch64
startup: services
boot: auto
network: host
options:
  - TWINGATE_NETWORK: "your-network"
  - TWINGATE_ACCESS_TOKEN": "your-access-token"
  - TWINGATE_REFRESH_TOKEN": "your-refresh-token"
schema:
  - TWINGATE_NETWORK: str
  - TWINGATE_ACCESS_TOKEN": str
  - TWINGATE_REFRESH_TOKEN": str
map:
  - "config"