name: "Twingate Connector"
description: "Runs the Twingate Connector inside Home Assistant OS"
version: "0.1.3"
slug: "twingate_connector"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
schema:
  network_slug: str
  access_token: str
  refresh_token: str
